name: Deploy Serverless to DEV/TEST

on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: true
      ENV_NAME:
        type: string
        required: true
      CF_DISTRIBUTION_ID:
        type: string
        required: true
    secrets:
      GITHUB_PACKAGE_ACCESS_TOKEN:
        required: true
      SHARED_ACTIONS_SSH_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCESS_KEY_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          repository: boma-marketing/gh-actions
          ref: v2
          path: ./.github/actions/boma

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: ./.github/actions/boma/install-from-cache
        with:
          node-auth-token: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}

      - name: Build and store artifacts for env
        uses: ./.github/actions/boma/build-spa
        with:
          app-name: ${{ inputs.APP_NAME }}
          env-name: ${{ inputs.ENV_NAME}}
          node-auth-token: ${{ secrets.GITHUB_PACKAGE_ACCESS_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SHARED_ACTIONS_SSH_KEY }}
          repository: boma-marketing/gh-actions
          ref: v2
          path: ./.github/actions/boma

      - name: Deploy to Environment
        uses: ./.github/actions/boma/deploy-spa
        with:
          app-name: ${{ inputs.APP_NAME }}
          env-name: ${{ inputs.ENV_NAME}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          cf-distribution-id: ${{ inputs.CF_DISTRIBUTION_ID }}

